[collection]
name = "Pissaro"
description = "Tranquil rural landscapes and village scenes with a soft, luminous touch that emphasized everyday country life."

# ─────────────────────────────────────────────
# Camille Pissarro
# ─────────────────────────────────────────────

[sub.pissarro]
name = "Camille Pissarro"
description = "Village streets, soft light, and the poetry of everyday life."
default_artist = "Camille Pissarro"

[[sub.pissarro.items]]
museum = "nga"
object = "e291058c-0769-493c-a5f3-8e0e64e9ea46"
title = "The Artist's Garden at Eragny"
date = "1898"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Landscape", "Garden"]

[[sub.pissarro.items]]
museum = "nga"
object = "1921981a-82c4-46ee-8cec-185aa18e2538"
title = "Boulevard des Italiens, Morning, Sunlight"
date = "1897"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Cityscape", "Paris"]

[[sub.pissarro.items]]
museum = "nga"
object = "b4419dc5-cea3-4a69-9c48-60a896901ca1"
title = "Charing Cross Bridge, London"
date = "1890"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Cityscape", "London"]

[[sub.pissarro.items]]
museum = "nga"
object = "f7896300-10dd-4eec-ae25-bf689ce99015"
title = "The Louvre, Afternoon, Rainy Weather"
date = "1900"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Cityscape", "Paris"]

[[sub.pissarro.items]]
museum = "nga"
object = "2f61c3b8-00ff-41d4-941a-9d639c291472"
title = "Place du Carrousel, Paris"
date = "1900"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Cityscape", "Paris"]

[[sub.pissarro.items]]
museum = "nga"
object = "94413b0f-688f-4cf4-9a08-f52e836faab4"
title = "The Fence"
date = "1872"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Landscape"]

[[sub.pissarro.items]]
museum = "nga"
object = "fdfa01c4-7334-4a34-a1fa-64429773e96e"
title = "Two Women Chatting by the Sea, St. Thomas"
date = "1897"
medium = "Oil on canvas"
classification = "Painting"
subjects = ["Landscape", "St. Thomas"]


# Items to add:
# The Avenue, Sydenham (1871)
# National Gallery, London UK PID NG6493

# Pissarro's Hyde Park (1890)
# Tokyo Fuji Art Museum

[[sub.pissarro.items]]
#Piette’s House at Montfoucault: Snow Effect (1874)
#Clark Art Institute, Williamstown, MA 1955.826
museum = "wikimedia"
object = "Pissarro_-_Piette%27s_House_at_Montfoucault,_1874.jpg"
title = "Piette’s House at Montfoucault: Snow Effect"
Style = "Impressionism"
subjects = ["Snow", "Winter"]

[[sub.pissarro.items]]
# Boulevard Montmartre on a winter morning (1897)
# met ID 437310
# https://collectionapi.metmuseum.org/public/collection/v1/objects/[objectID]
museum = "met"
object = "437310"

[[sub.pissarro.items]]
#Boulevard Montmartre in springtime.
museum = "wikimedia"
object = "Camille_Pissarro_-_Boulevard_Montmartre,_Spring_-_Google_Art_Project.jpg"
title = "Boulevard Montmartre in Springtime"
Style = "Impressionism"
subjects = ["Street", "Spring", "Cityscape"]

[[sub.pissarro.items]]
museum = "wikimedia"
object = "Camille_Pissarro_-_Boulevard_Montmartre_-_Eremitage.jpg"
Style = "Impressionism"
title = "Boulevard Montmartre"
subjects = ["Street", "Fall", "Cityscape"]

[[sub.pissarro.items]]
# Tuileries Gardens (Winter Afternoon) (1899)
# MET ID 437314
museum = "met"
object = "437314"
